'use client';
import React,{useEffect,useRef,useState}from'react';
import {base44}from'@/api/base44Client';
import {mwakwaData,type MwakwaUser}from'@/lib/mwakwaBackend';

type Props={user:MwakwaUser|null};type Row=Record<string,unknown>&{id?:string;title?:string};type ScanResult={success?:boolean;result?:string;message?:string;event?:{id?:string;title?:string};ticket?:{id?:string;type?:string;buyer_email?:string}};type BarcodeDetectorCtor=new(options:{formats:string[]})=>{detect(video:HTMLVideoElement):Promise<Array<{rawValue?:string}>>};
export default function TicketScanner({user}:Props){const[events,setEvents]=useState<Row[]>([]),[eventId,setEventId]=useState(''),[code,setCode]=useState(''),[result,setResult]=useState<ScanResult|null>(null),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false);const videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null),timerRef=useRef<number|undefined>(undefined);
 useEffect(()=>{if(user)mwakwaData.events.filter({organizer_id:user.id},'-event_date',100,0).then(setEvents).catch(console.error);return()=>stopCamera()},[user]);
 const check=async(raw:string)=>{const value=raw.trim();if(!value||busy)return;setBusy(true);try{const r=await base44.functions.invoke('check-in-ticket',{qr_code:value,event_id:eventId||undefined,device_reference:typeof navigator!=='undefined'?navigator.userAgent.slice(0,180):undefined});setResult(r.data);if(r.data?.success)setCode('')}catch(e:unknown){const message=e instanceof Error?e.message:'Check-in failed';setResult({success:false,result:'error',message})}finally{setBusy(false)}};
 const stopCamera=()=>{if(timerRef.current)window.clearInterval(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCamera(false)};
 const startCamera=async()=>{if(!('BarcodeDetector'in window)){setResult({success:false,message:'Live QR scanning is not supported by this browser. Use the ticket code field instead.'});return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCamera(true);const Detector=(window as unknown as {BarcodeDetector:BarcodeDetectorCtor}).BarcodeDetector;const detector=new Detector({formats:['qr_code']});timerRef.current=window.setInterval(async()=>{if(!videoRef.current||busy)return;try{const hits=await detector.detect(videoRef.current);if(hits?.[0]?.rawValue){stopCamera();await check(hits[0].rawValue)}}catch{}},500)}catch(e:unknown){setResult({success:false,message:e instanceof Error?e.message:'Camera unavailable'})}};
 const tone=result?.success?'border-green-300 bg-green-50 text-green-900':result?'border-red-300 bg-red-50 text-red-900':'border-gray-200 bg-white';
 return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Ticket Scanner</h2><p className="text-sm text-gray-600 mt-1">Scan at the entrance or enter a ticket code manually. A successful scan immediately marks the ticket used, so repeat scans are rejected.</p></div><div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5 space-y-4"><label className="block text-sm font-medium">Event</label><select className="w-full border rounded-lg px-3 py-3" value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Any of my events</option>{events.map(e=><option key={e.id} value={String(e.id||'')}>{String(e.title||'Untitled event')}</option>)}</select><div className="flex gap-2"><input className="flex-1 border rounded-lg px-3 py-3" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')check(code)}} placeholder="Scan or enter ticket code" autoCapitalize="characters"/><button disabled={busy||!code.trim()} onClick={()=>check(code)} className="rounded-lg bg-blue-600 disabled:bg-gray-300 text-white px-5">{busy?'Checking…':'Check in'}</button></div><button onClick={camera?stopCamera:startCamera} className="w-full rounded-lg border px-4 py-3">{camera?'Stop camera':'Open QR camera'}</button><video ref={videoRef} playsInline muted className={`${camera?'block':'hidden'} w-full rounded-xl bg-black aspect-video object-cover`}/></section><section className={`border rounded-xl p-6 ${tone}`}><h3 className="font-semibold text-lg">Gate result</h3>{!result?<p className="mt-3 text-sm">Waiting for a ticket.</p>:<div className="mt-3 space-y-2"><p className="text-2xl font-bold">{result.success?'ACCESS GRANTED':'DO NOT ADMIT'}</p><p>{result.message}</p>{result.event?.title&&<p className="text-sm"><b>Event:</b> {result.event.title}</p>}{result.ticket?.type&&<p className="text-sm"><b>Ticket:</b> {result.ticket.type}</p>}{result.ticket?.buyer_email&&<p className="text-sm"><b>Buyer:</b> {result.ticket.buyer_email}</p>}</div>}</section></div><p className="text-xs text-gray-500">The server validates organizer/staff access, event ownership and ticket status. Cancelled, refunded, invalid and already-used tickets cannot be admitted.</p></div>}
