"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {mwakwaAuth,mwakwaData,type MwakwaUser} from "@/lib/mwakwaBackend";
type Row=Record<string, unknown> & { id?:string; status?:string; currency?:string; organizer_id?:string; available_amount?:number; pending_amount?:number; held_amount?:number; negative_amount?:number; payouts_frozen?:boolean; request_type?:string; amount?:number; eligibility?:string; liability_party?:string; dispute_type?:string; amount_at_risk?:number; hold_amount?:number; gross_sales?:number; reserve_held?:number; net_amount?:number; kyc_status?:string; organization_name?:string; user_id?:string; }; const money=(n:unknown,c:unknown="XAF")=>`${String(c||"XAF")} ${Number(n||0).toLocaleString()}`;
export default function Operations(){const [user,setUser]=useState<MwakwaUser|null>(null),[loading,setLoading]=useState(true),[balances,setBalances]=useState<Row[]>([]),[refunds,setRefunds]=useState<Row[]>([]),[disputes,setDisputes]=useState<Row[]>([]),[payouts,setPayouts]=useState<Row[]>([]),[profiles,setProfiles]=useState<Row[]>([]);
 const load=async()=>{const me=await mwakwaAuth.me();setUser(me);if(me?.role!=="admin"){setLoading(false);return}const [b,r,d,p,o]=await Promise.all([mwakwaData.organizerBalances.list("-updated_date",100,0),mwakwaData.refundRequests.list("-created_date",100,0),mwakwaData.disputes.list("-created_date",100,0),mwakwaData.organizerPayouts.list("-created_date",100,0),mwakwaData.organizerProfiles.list("-created_date",100,0)]);setBalances(b);setRefunds(r);setDisputes(d);setPayouts(p);setProfiles(o);setLoading(false)};useEffect(()=>{load()},[]);
 const update=async(entity:{update:(id:string,data:Record<string,unknown>)=>Promise<unknown>},row:Row,patch:Record<string,unknown>)=>{await entity.update(String(row.id),patch);if(user){await mwakwaData.auditLogs.create({actor_id:user.id,actor_role:user.role||"admin",action:"admin_update",entity_type:"operation_record",entity_id:String(row.id),before:row,after:{...row,...patch},occurred_at:new Date().toISOString()})}await load()}; if(loading)return <main className="p-8">Loading…</main>;if(user?.role!=="admin")return <main className="p-8"><h1 className="text-2xl font-bold">Admin access required</h1></main>;
 return <main className="min-h-screen bg-gray-50 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-8"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Mwakwa Operations</h1><p className="text-gray-600">Organizer risk, refunds, disputes and payouts.</p></div><Link href="/admin/cms" className="bg-white border rounded-lg px-4 py-2">CMS & policies</Link></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[["Organizer balances",balances.length],["Open refunds",refunds.filter(r=>!["completed","rejected"].includes(String(r.status||""))).length],["Open disputes",disputes.filter(d=>!["closed","resolved_buyer","resolved_organizer"].includes(String(d.status||""))).length],["Pending payouts",payouts.filter(p=>["draft","pending","processing","held"].includes(String(p.status||""))).length]].map(([l,v])=><div className="bg-white border rounded-xl p-5" key={String(l)}><p className="text-sm text-gray-500">{l}</p><p className="text-3xl font-bold">{String(v)}</p></div>)}</div>
 <section className="bg-white border rounded-xl p-5"><h2 className="text-xl font-bold mb-4">Organizer balances</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2">Organizer</th><th>Available</th><th>Pending</th><th>Held</th><th>Owed</th><th>Risk</th></tr></thead><tbody>{balances.map(b=><tr className="border-b" key={b.id}><td className="py-3">{b.organizer_id}</td><td>{money(b.available_amount,b.currency)}</td><td>{money(b.pending_amount,b.currency)}</td><td>{money(b.held_amount,b.currency)}</td><td>{money(b.negative_amount,b.currency)}</td><td>{b.payouts_frozen?<span className="text-red-700 font-medium">Payouts frozen</span>:"Clear"}</td></tr>)}</tbody></table></div></section>
 <div className="grid xl:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5"><h2 className="text-xl font-bold mb-4">Refund queue</h2>{refunds.length===0?<p className="text-gray-500">No refund requests.</p>:refunds.map(r=><div key={r.id} className="border-b py-4"><div className="flex justify-between"><b>{r.request_type?.replaceAll("_"," ")}</b><span>{money(r.amount,r.currency)}</span></div><p className="text-sm text-gray-500">{r.status} · {r.eligibility} · liability: {r.liability_party}</p><div className="flex gap-2 mt-2">{r.status==="requested"&&<><button onClick={()=>update(mwakwaData.refundRequests,r,{status:"approved",eligibility:"eligible"})} className="bg-green-700 text-white rounded px-3 py-1">Approve</button><button onClick={()=>update(mwakwaData.refundRequests,r,{status:"rejected"})} className="bg-red-700 text-white rounded px-3 py-1">Reject</button></>}</div></div>)}</section>
 <section className="bg-white border rounded-xl p-5"><h2 className="text-xl font-bold mb-4">Disputes</h2>{disputes.length===0?<p className="text-gray-500">No disputes.</p>:disputes.map(d=><div key={d.id} className="border-b py-4"><div className="flex justify-between"><b>{d.dispute_type?.replaceAll("_"," ")}</b><span>{money(d.amount_at_risk,d.currency)}</span></div><p className="text-sm text-gray-500">{d.status} · hold {money(d.hold_amount,d.currency)}</p>{d.status==="open"&&<button onClick={()=>update(mwakwaData.disputes,d,{status:"under_review",assigned_to:user.id})} className="mt-2 border rounded px-3 py-1">Start review</button>}</div>)}</section></div>
 <section className="bg-white border rounded-xl p-5"><h2 className="text-xl font-bold mb-4">Payout queue</h2>{payouts.length===0?<p className="text-gray-500">No payout records.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2">Organizer</th><th>Status</th><th>Gross</th><th>Reserve</th><th>Net</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id} className="border-b"><td className="py-3">{p.organizer_id}</td><td>{p.status}</td><td>{money(p.gross_sales,p.currency)}</td><td>{money(p.reserve_held,p.currency)}</td><td>{money(p.net_amount,p.currency)}</td></tr>)}</tbody></table></div>}</section>
 <section className="bg-white border rounded-xl p-5"><h2 className="text-xl font-bold mb-4">Organizer verification</h2>{profiles.filter(p=>p.kyc_status==="pending").length===0?<p className="text-gray-500">No organizer profiles awaiting review.</p>:profiles.filter(p=>p.kyc_status==="pending").map(p=><div key={p.id} className="flex flex-wrap justify-between gap-3 border-b py-3"><div><b>{p.organization_name||p.user_id}</b><p className="text-sm text-gray-500">KYC pending</p></div><div className="flex gap-2"><button onClick={()=>update(mwakwaData.organizerProfiles,p,{kyc_status:"approved",rejection_reason:""})} className="bg-green-700 text-white rounded px-3 py-1">Approve</button><button onClick={()=>update(mwakwaData.organizerProfiles,p,{kyc_status:"rejected",rejection_reason:"Manual review rejected"})} className="bg-red-700 text-white rounded px-3 py-1">Reject</button></div></div>)}</section>
 </div></main>}
